# Generated by Django 3.0.5 on 2020-04-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='', upload_to='users/foto', verbose_name='Фото')),
                ('nik', models.CharField(max_length=15, verbose_name='Ник')),
                ('firstname', models.CharField(max_length=15, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('pfone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('dborn', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Email')),
                ('rate', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
        ),
    ]
