# Generated by Django 3.0.5 on 2020-04-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200404_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='flightday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, verbose_name='Дата полетов')),
                ('timestart', models.TimeField(blank=True, verbose_name='Время начала полетов')),
                ('timefinish', models.TimeField(blank=True, verbose_name='Время окончания полетов')),
                ('nalet', models.TimeField(blank=True, verbose_name='Максимальный налет')),
                ('info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'День полетов',
                'verbose_name_plural': 'Дни полетов',
                'ordering': ['data'],
            },
        ),
    ]
