# Generated by Django 3.0.5 on 2020-04-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_flightday'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightday',
            name='regopen',
            field=models.BooleanField(default=False, verbose_name='Регистрация открыта'),
        ),
    ]
