# Generated by Django 3.0.5 on 2020-04-05 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_flightday_regopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightday',
            name='data',
            field=models.DateField(blank=True, unique=True, verbose_name='Дата полетов'),
        ),
        migrations.CreateModel(
            name='zapisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zapisi', models.DateField(auto_now_add=True, unique=True, verbose_name='Дата записи')),
                ('coment', models.TextField(blank=True, verbose_name='Коментарий')),
                ('chlen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.user')),
                ('data_poleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.flightday')),
            ],
            options={
                'verbose_name': 'Запись на полеты',
                'verbose_name_plural': 'Записи на полеты',
                'ordering': ['data_poleta'],
            },
        ),
    ]
