# Generated by Django 3.0.5 on 2020-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200405_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapisi',
            name='data_zapisi',
            field=models.DateField(auto_now=True, verbose_name='Дата записи'),
        ),
    ]
