# Generated by Django 3.0.5 on 2020-04-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_user_user_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='connect_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='профиль')),
                ('user_reg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='зарегистрированный пользователь')),
            ],
            options={
                'verbose_name': 'связь с профилем',
                'verbose_name_plural': 'связи с профилем',
            },
        ),
    ]
