# Generated by Django 3.0.5 on 2020-04-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_connect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dborn',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
